### ISSUE TITLE
bot sold spirit shield and not using it for cta

### ISSUE THREAD

**Issue by mato89** [isid0re/SoloLeveling#380] opened 2021-12-26 16:33 UTC
My hammerdin has been using a spirit shield in his main hand and a CTA off-hand. 
After it picked up a hoz it sold the spirit shield and the off-hand slot has remained shield-less for quite a few days...

**Comment by isid0re** [comment] 2021-12-31 05:23
Thank you for posting the problem. I looked into it and found the cause. I've already pushed a fix to the repo.

Thanks again.

**Closed** 2021-12-31 05:23 UTC
