### ISSUE TITLE
Bot having issues with fallen/shamens/won't clear areas

### ISSUE THREAD

**Issue by JediPeaceFrog** [isid0re/SoloLeveling#216] opened 2021-04-21 21:28 UTC
Hello...thanks for the program and your effort.  it's very much appreciated.  having issues running a HCL-PAL---took 25 tries to finish Den...currently running around cold plains doing nothing but sparring with fallen/fallen shamens.   shamens keep resurrecting, bot spends an hour killing same fallen over and over.  also, keeps dying then doesn't make new game.  currently bot is on its 7th hour, and still not past cold plains.    anything i did wrong?  thanks!

**Comment by JediPeaceFrog** [comment] 2021-04-22 01:32
AS far as the died and won't create game, i've fixed that utilizing fixit from other post.

seems to be working now, but game keeps crashing.   normal kolbot never crashed on me like this does...exits game every 5 minutes or so.

**Comment by isid0re** [comment] 2021-04-23 01:53
The it is a project. So some features can be unstable at times as I build this out. But I am working to improve stability. 

Regarding your comment about "25 times"  I would need context to better understand what the issue is. 

For example 
What character level and Build it's running etc

**Comment by JediPeaceFrog** [comment] 2021-04-23 02:05
Paladin.   smiter.   i'm not trying to offend you...the effort is appreciated.  just wanted to let you know this latest version just isn't working right.   i'm trying wind druid single player and paladin/smiter bnet.   the sp wind druid seems to run better...moving along more rapidly and is not going back to countess/andy/trav constantly.  but the pally got to act 4, then stopped, quit game, and now is on its 25th game going back to countess.  keeps going back to act 3 to gather eye, brain etc for flail for trav....25 times!   i stop the program, start it back up...same thing.  starts back at countess, goes andy, then goes through act 3 again.  i never realized that on bnet it wouldn't keep the trav door open for durance level 1...thought that once it was opened, it's opened..   the bot even grabbed durance wp.   yeah i'm at a loss to what's happening here.   but one thing is for sure:  the pally needs work..

**Comment by JediPeaceFrog** [comment] 2021-04-23 02:06
^ nightmare

**Comment by isid0re** [comment] 2021-04-23 02:17
Could you compare your globals.js check task function vs the repo version.

Especially, the brain, eye, heart portion. If they dont match please update your files, if they do match then please let me know. Because I believe the repeated scripts should be fixed.

**Comment by isid0re** [comment] 2021-05-06 17:12
No reply if updating fixed so closing

**Closed** 2021-05-06 17:13 UTC
