### ISSUE TITLE
Error in SoloLeveling (misc.js #1374) - Stalling loop

### ISSUE THREAD

**Issue by jonkthx** [isid0re/SoloLeveling#159] opened 2021-03-04 17:32 UTC
Hello, I've noticed so far only my necro and pal (level 9-10) keep stalling while leveling with this error :
Error in SoloLeveling (misc.js #1374) unit is undefined 

They try to buy/sell at Charsis but stall with an item on cursor with this error. It can loop 3-4 times making new game and stall. Then somehow it will starts to work again and keep leveling.

Btw thanks for  your great work! Your tool is awesome 👍 

![image](https://user-images.githubusercontent.com/80061076/110005017-0ac5f580-7ce6-11eb-9a22-7fb970cb9f38.png)

**Comment by isid0re** [comment] 2021-03-04 17:57
Thank you. Someone mentioned this to me about an hour ago. Its caused by the last update. So I will be fixing it soon. Thanks again.

**Comment by jonkthx** [comment] 2021-03-04 21:07
Thanks a lot for your quick reply! This isnt a big deal since my 3 bots are leveling quickly even if I still sometime get this error.

Can't wait for the discord 👍  keep the good work!

**Comment by isid0re** [comment] 2021-03-05 06:00
the discord server is now up. Link is here: https://discord.gg/2JAAWBCQnb

**Comment by isid0re** [comment] 2021-03-24 01:11
Bug has been fixed in current push

**Closed by isid0re** 2021-03-24 01:11 UTC
